name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Maven
        run: |
          cd department-service
          mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          cd department-service
          docker build -t department-service:v1 .

  deploy:
    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop existing containers
        run: |
          cd department-service
          docker compose down || true

      - name: Run Docker Compose
        run: |
          cd department-service
          docker compose up -d --build